import type { ChatMessage, Family, Gap, Person } from "@/lib/types";

/**
 * The Alvarez–Chen family: four generations, one migration, plenty of holes.
 * Deliberately incomplete — the gaps are what the AI Interviewer exists for.
 */

const places: Family["places"] = [
  {
    id: "pl-oaxaca",
    name: "Oaxaca de Juárez, Mexico",
    shortName: "Oaxaca",
    lat: 17.0732,
    lng: -96.7266,
    kind: "historical",
  },
  {
    id: "pl-juarez",
    name: "Ciudad Juárez, Mexico",
    shortName: "Cd. Juárez",
    lat: 31.6904,
    lng: -106.4245,
    kind: "historical",
  },
  {
    id: "pl-chicago",
    name: "Pilsen, Chicago, Illinois",
    shortName: "Chicago",
    lat: 41.8571,
    lng: -87.6564,
    kind: "current",
  },
  {
    id: "pl-sf",
    name: "San Francisco, California",
    shortName: "San Francisco",
    lat: 37.7749,
    lng: -122.4194,
    kind: "historical",
  },
  {
    id: "pl-boston",
    name: "Somerville, Massachusetts",
    shortName: "Boston",
    lat: 42.3876,
    lng: -71.0995,
    kind: "current",
  },
  {
    id: "pl-austin",
    name: "Austin, Texas",
    shortName: "Austin",
    lat: 30.2672,
    lng: -97.7431,
    kind: "current",
  },
];

const people: Person[] = [
  {
    id: "p-josefa",
    name: "Josefa Ruiz",
    fullName: "Josefa Ruiz Méndez",
    nickname: "Mamá Fefa",
    birthYear: 1915,
    deathYear: 1998,
    isLiving: false,
    generation: 0,
    parentIds: [],
    spouseIds: [],
    birthPlaceId: "pl-oaxaca",
    bio: "Wove and sold rebozos in the Oaxaca market for fifty years. Stayed behind when the family went north.",
    contributedCount: 0,
  },
  {
    id: "p-tomas",
    name: "Tomás Alvarez",
    fullName: "Tomás Alvarez Cruz",
    nickname: "Abuelo",
    birthYear: 1938,
    deathYear: 2019,
    isLiving: false,
    generation: 1,
    parentIds: [],
    spouseIds: ["p-rosa"],
    birthPlaceId: "pl-oaxaca",
    bio: "Worked thirty-one years at the Wisconsin Steel Works. Never once talked about the trip north.",
    contributedCount: 0,
  },
  {
    id: "p-rosa",
    name: "Rosa Alvarez",
    fullName: "Rosa Ruiz de Alvarez",
    nickname: "Abuela Rosa",
    birthYear: 1941,
    deathYear: null,
    isLiving: true,
    generation: 1,
    parentIds: ["p-josefa"],
    spouseIds: ["p-tomas"],
    birthPlaceId: "pl-oaxaca",
    currentPlaceId: "pl-chicago",
    bio: "Still lives in the Pilsen apartment she moved into in 1968. Makes the mole everyone drives in for.",
    contributedCount: 14,
    prefersVoice: true,
  },
  {
    id: "p-elena",
    name: "Elena Alvarez",
    birthYear: 1969,
    deathYear: null,
    isLiving: true,
    generation: 2,
    parentIds: ["p-rosa", "p-tomas"],
    spouseIds: ["p-david"],
    birthPlaceId: "pl-chicago",
    currentPlaceId: "pl-chicago",
    bio: "First in the family born in the United States. Taught third grade at Orozco for twenty-six years.",
    contributedCount: 6,
  },
  {
    id: "p-david",
    name: "David Chen",
    birthYear: 1967,
    deathYear: null,
    isLiving: true,
    generation: 2,
    parentIds: [],
    spouseIds: ["p-elena"],
    birthPlaceId: "pl-sf",
    currentPlaceId: "pl-chicago",
    bio: "Married into the family in 1994 and has run the carne asada ever since.",
    contributedCount: 2,
  },
  {
    id: "p-miguel",
    name: "Miguel Alvarez",
    birthYear: 1972,
    deathYear: null,
    isLiving: true,
    generation: 2,
    parentIds: ["p-rosa", "p-tomas"],
    spouseIds: ["p-ana"],
    birthPlaceId: "pl-chicago",
    currentPlaceId: "pl-chicago",
    bio: "Runs the auto shop on 18th Street that Tomás bought into in 1981.",
    contributedCount: 3,
  },
  {
    id: "p-ana",
    name: "Ana Reyes",
    birthYear: 1975,
    deathYear: null,
    isLiving: true,
    generation: 2,
    parentIds: [],
    spouseIds: ["p-miguel"],
    currentPlaceId: "pl-chicago",
    bio: "Keeps every photograph anyone has ever handed her, in eleven shoeboxes.",
    contributedCount: 9,
  },
  {
    id: "p-maya",
    name: "Maya Chen",
    birthYear: 1996,
    deathYear: null,
    isLiving: true,
    generation: 3,
    parentIds: ["p-elena", "p-david"],
    spouseIds: [],
    birthPlaceId: "pl-chicago",
    currentPlaceId: "pl-boston",
    bio: "Started Keepsake after realizing nobody had ever recorded Abuela telling the 1968 story.",
    contributedCount: 21,
  },
  {
    id: "p-leo",
    name: "Leo Chen",
    birthYear: 1999,
    deathYear: null,
    isLiving: true,
    generation: 3,
    parentIds: ["p-elena", "p-david"],
    spouseIds: [],
    birthPlaceId: "pl-chicago",
    currentPlaceId: "pl-austin",
    bio: "Plays in a band that is, by his own admission, mostly a group chat.",
    contributedCount: 1,
  },
  {
    id: "p-sofia",
    name: "Sofía Alvarez",
    birthYear: 2004,
    deathYear: null,
    isLiving: true,
    generation: 3,
    parentIds: ["p-miguel", "p-ana"],
    spouseIds: [],
    birthPlaceId: "pl-chicago",
    currentPlaceId: "pl-chicago",
    bio: "Interviewing Abuela for a class project is what gave Maya the idea.",
    contributedCount: 4,
  },
];

const events: Family["events"] = [
  {
    id: "e-josefa-born",
    title: "Josefa Ruiz is born",
    date: "1915",
    datePrecision: "year",
    scope: "canon",
    category: "birth",
    personIds: ["p-josefa"],
    placeId: "pl-oaxaca",
    summary: "Born in a house on Calle Tinoco y Palacios that is still standing.",
    sourceMemoryIds: [],
    confidence: 0.72,
  },
  {
    id: "e-tomas-born",
    title: "Tomás Alvarez is born",
    date: "1938-03",
    datePrecision: "month",
    scope: "canon",
    category: "birth",
    personIds: ["p-tomas"],
    placeId: "pl-oaxaca",
    summary: "The eldest of six. Left school at eleven to work.",
    sourceMemoryIds: ["m-rosa-wedding"],
    confidence: 0.88,
  },
  {
    id: "e-rosa-born",
    title: "Rosa Ruiz is born",
    date: "1941-08-14",
    datePrecision: "day",
    scope: "canon",
    category: "birth",
    personIds: ["p-rosa"],
    placeId: "pl-oaxaca",
    summary: "Josefa's only daughter, born during the rains.",
    sourceMemoryIds: [],
    confidence: 0.95,
  },
  {
    id: "e-lemon-tree",
    title: "The lemon tree in the courtyard",
    date: "1949",
    datePrecision: "year",
    scope: "individual",
    category: "anecdote",
    personIds: ["p-rosa"],
    placeId: "pl-oaxaca",
    summary:
      "Rosa and her cousins slept under it in summer because the house held the heat. She can still describe the sound of the leaves.",
    sourceMemoryIds: ["m-rosa-lemon"],
    confidence: 0.91,
  },
  {
    id: "e-rosa-sewing",
    title: "Learns to sew at twelve",
    date: "1953",
    datePrecision: "year",
    scope: "individual",
    category: "milestone",
    personIds: ["p-rosa", "p-josefa"],
    placeId: "pl-oaxaca",
    summary: "Josefa taught her on a treadle machine. Rosa made her own wedding dress nine years later.",
    sourceMemoryIds: ["m-rosa-lemon"],
    confidence: 0.83,
  },
  {
    id: "e-wedding",
    title: "Rosa and Tomás marry",
    date: "1962-11-24",
    datePrecision: "day",
    scope: "canon",
    category: "marriage",
    personIds: ["p-rosa", "p-tomas"],
    placeId: "pl-oaxaca",
    summary: "Married at Santo Domingo with forty people and one photographer who never delivered the photos.",
    sourceMemoryIds: ["m-rosa-wedding"],
    confidence: 0.94,
  },
  {
    id: "e-leaving",
    title: "The family leaves Oaxaca",
    date: "1968-04",
    datePrecision: "month",
    scope: "canon",
    category: "migration",
    personIds: ["p-rosa", "p-tomas"],
    placeId: "pl-oaxaca",
    summary:
      "Rosa and Tomás left with two suitcases and Josefa's address book. The reason has never been written down.",
    sourceMemoryIds: ["m-maya-note"],
    confidence: 0.58,
  },
  {
    id: "e-juarez",
    title: "Six weeks in Ciudad Juárez",
    date: "1968-05",
    datePrecision: "month",
    scope: "canon",
    category: "migration",
    personIds: ["p-rosa", "p-tomas"],
    placeId: "pl-juarez",
    summary: "They waited on paperwork. Tomás swept a bakery for room and board.",
    sourceMemoryIds: [],
    confidence: 0.49,
  },
  {
    id: "e-arrival",
    title: "Arrival in Pilsen",
    date: "1968-07-02",
    datePrecision: "day",
    scope: "canon",
    category: "migration",
    personIds: ["p-rosa", "p-tomas"],
    placeId: "pl-chicago",
    summary:
      "A cousin met them at Union Station. They moved into the second-floor apartment on 19th Place where Rosa still lives.",
    sourceMemoryIds: ["m-rosa-arrival"],
    confidence: 0.9,
  },
  {
    id: "e-elena-born",
    title: "Elena is born",
    date: "1969-09-30",
    datePrecision: "day",
    scope: "canon",
    category: "birth",
    personIds: ["p-elena"],
    placeId: "pl-chicago",
    summary: "The first of the family born in the United States.",
    sourceMemoryIds: [],
    confidence: 0.97,
  },
  {
    id: "e-steel",
    title: "Night shifts at Wisconsin Steel",
    date: "1970",
    datePrecision: "year",
    scope: "individual",
    category: "milestone",
    personIds: ["p-tomas"],
    placeId: "pl-chicago",
    summary: "Eleven years of nights so he could be home in the afternoons. He never called it a sacrifice.",
    sourceMemoryIds: ["m-elena-dad"],
    confidence: 0.86,
  },
  {
    id: "e-miguel-born",
    title: "Miguel is born",
    date: "1972-01-18",
    datePrecision: "day",
    scope: "canon",
    category: "birth",
    personIds: ["p-miguel"],
    placeId: "pl-chicago",
    summary: "Born during the blizzard that shut the city for three days.",
    sourceMemoryIds: [],
    confidence: 0.93,
  },
  {
    id: "e-radio",
    title: "Learns English from the radio",
    date: "1974",
    datePrecision: "year",
    scope: "individual",
    category: "anecdote",
    personIds: ["p-elena", "p-rosa"],
    placeId: "pl-chicago",
    summary:
      "Elena translated for her mother at the clinic by the time she was seven, having learned most of it from WLS.",
    sourceMemoryIds: ["m-elena-dad"],
    confidence: 0.79,
  },
  {
    id: "e-shop",
    title: "Tomás buys into the shop on 18th",
    date: "1981",
    datePrecision: "year",
    scope: "canon",
    category: "milestone",
    personIds: ["p-tomas", "p-miguel"],
    placeId: "pl-chicago",
    summary: "Half of a two-bay garage, paid for over four years. Miguel runs it now.",
    sourceMemoryIds: [],
    confidence: 0.81,
  },
  {
    id: "e-elena-david",
    title: "Elena marries David",
    date: "1994-06-11",
    datePrecision: "day",
    scope: "canon",
    category: "marriage",
    personIds: ["p-elena", "p-david"],
    placeId: "pl-chicago",
    summary: "Rosa wore the same rebozo Josefa wore in 1962.",
    sourceMemoryIds: [],
    confidence: 0.96,
  },
  {
    id: "e-maya-born",
    title: "Maya is born",
    date: "1996-02-08",
    datePrecision: "day",
    scope: "canon",
    category: "birth",
    personIds: ["p-maya"],
    placeId: "pl-chicago",
    summary: "",
    sourceMemoryIds: [],
    confidence: 0.98,
  },
  {
    id: "e-josefa-dies",
    title: "Josefa dies in Oaxaca",
    date: "1998-11",
    datePrecision: "month",
    scope: "canon",
    category: "death",
    personIds: ["p-josefa"],
    placeId: "pl-oaxaca",
    summary: "Rosa flew back for the first time in thirty years.",
    sourceMemoryIds: [],
    confidence: 0.87,
  },
  {
    id: "e-leo-guitar",
    title: "The pawn shop guitar",
    date: "2010",
    datePrecision: "year",
    scope: "individual",
    category: "anecdote",
    personIds: ["p-leo", "p-tomas"],
    placeId: "pl-chicago",
    summary: "Tomás bought it for forty dollars and told Leo it had belonged to someone famous. It had not.",
    sourceMemoryIds: [],
    confidence: 0.74,
  },
  {
    id: "e-tomas-dies",
    title: "Tomás dies",
    date: "2019-03-16",
    datePrecision: "day",
    scope: "canon",
    category: "death",
    personIds: ["p-tomas"],
    placeId: "pl-chicago",
    summary: "Eighty-one years old, in the apartment, with the television on.",
    sourceMemoryIds: [],
    confidence: 0.99,
  },
  {
    id: "e-maya-boston",
    title: "Maya moves to Boston",
    date: "2018-08",
    datePrecision: "month",
    scope: "individual",
    category: "milestone",
    personIds: ["p-maya"],
    placeId: "pl-boston",
    summary: "The first Alvarez to leave Chicago since 1968. Rosa did not speak to her for a week.",
    sourceMemoryIds: ["m-maya-note"],
    confidence: 0.88,
  },
  {
    id: "e-sofia-project",
    title: "Sofía records Abuela for a class project",
    date: "2025-10",
    datePrecision: "month",
    scope: "individual",
    category: "milestone",
    personIds: ["p-sofia", "p-rosa"],
    placeId: "pl-chicago",
    summary: "Forty minutes of tape that nobody in the family had ever thought to make.",
    sourceMemoryIds: ["m-sofia-tape"],
    confidence: 0.92,
  },
];

const memories: Family["memories"] = [
  {
    id: "m-rosa-lemon",
    kind: "voice",
    authorId: "p-rosa",
    createdAt: "2026-09-18T14:12:00Z",
    title: "The lemon tree",
    body: "In the summer we slept outside, under the lemon tree, because the house kept all the heat from the day. My cousins and me, all in a row. You could hear the leaves. I have not thought about that in years.",
    durationSec: 47,
    personIds: ["p-rosa"],
    placeId: "pl-oaxaca",
    derivedEventIds: ["e-lemon-tree", "e-rosa-sewing"],
    status: "ready",
  },
  {
    id: "m-sofia-tape",
    kind: "voice",
    authorId: "p-sofia",
    createdAt: "2026-09-18T02:40:00Z",
    title: "Abuela, forty minutes",
    body: "Sofía's class recording — the full interview. Still being split into separate stories.",
    durationSec: 2417,
    personIds: ["p-rosa", "p-sofia"],
    placeId: "pl-chicago",
    derivedEventIds: ["e-sofia-project"],
    status: "processing",
  },
  {
    id: "m-ana-photo",
    kind: "photo",
    authorId: "p-ana",
    createdAt: "2026-09-17T19:05:00Z",
    title: "Shoebox #4, unlabelled",
    body: "Six people on a stoop, 1972 or thereabouts. Rosa is second from the left. Nobody can name the man beside her.",
    mediaUrl: null,
    personIds: ["p-rosa"],
    placeId: "pl-chicago",
    derivedEventIds: [],
    status: "ready",
  },
  {
    id: "m-elena-dad",
    kind: "text",
    authorId: "p-elena",
    createdAt: "2026-09-16T23:31:00Z",
    title: "About Dad's shifts",
    body: "He worked nights for eleven years so he could pick us up from school. I only understood what that cost him after I had my own kids.",
    personIds: ["p-tomas", "p-elena"],
    placeId: "pl-chicago",
    derivedEventIds: ["e-steel", "e-radio"],
    status: "ready",
  },
  {
    id: "m-rosa-arrival",
    kind: "voice",
    authorId: "p-rosa",
    createdAt: "2026-09-15T16:20:00Z",
    title: "The first night on 19th Place",
    body: "There was no furniture. We slept on coats. Tomás said, tomorrow I find work, and he did, the very next day.",
    durationSec: 63,
    personIds: ["p-rosa", "p-tomas"],
    placeId: "pl-chicago",
    derivedEventIds: ["e-arrival"],
    status: "ready",
  },
  {
    id: "m-rosa-wedding",
    kind: "voice",
    authorId: "p-rosa",
    createdAt: "2026-09-14T11:02:00Z",
    title: "The wedding with no photographs",
    body: "The man took the pictures and we never saw him again. For sixty years I have had no pictures of that day. I remember the dress though. I made it myself.",
    durationSec: 55,
    personIds: ["p-rosa", "p-tomas"],
    placeId: "pl-oaxaca",
    derivedEventIds: ["e-wedding", "e-tomas-born"],
    status: "ready",
  },
  {
    id: "m-maya-note",
    kind: "text",
    authorId: "p-maya",
    createdAt: "2026-09-13T09:44:00Z",
    title: "Why I started this",
    body: "Abuelo died with the whole story in his head. I am not letting that happen twice.",
    personIds: ["p-maya", "p-tomas"],
    derivedEventIds: ["e-leaving", "e-maya-boston"],
    status: "ready",
  },
];

const gaps: Gap[] = [
  {
    id: "g-why-leave",
    question: "You and Abuelo left Oaxaca in the spring of 1968. What made you decide to go?",
    rationale:
      "The migration is the family's central event and the single largest hole in the record. No memory on file explains the decision.",
    subjectPersonId: "p-rosa",
    askPersonId: "p-rosa",
    relatedEventId: "e-leaving",
    priority: 100,
    status: "open",
  },
  {
    id: "g-first-meal",
    question: "What was the first thing you cooked in the Chicago apartment?",
    rationale: "Sensory detail around the 1968 arrival. Easy to answer, and it tends to unlock the harder ones.",
    subjectPersonId: "p-rosa",
    askPersonId: "p-rosa",
    relatedEventId: "e-arrival",
    priority: 78,
    status: "open",
  },
  {
    id: "g-stoop-photo",
    question: "In the photo on the stoop, who is standing next to you?",
    rationale: "Ana's unlabelled 1972 photograph has an unidentified adult male. Likely a relative we have no record of.",
    subjectPersonId: "p-rosa",
    askPersonId: "p-rosa",
    priority: 71,
    status: "open",
  },
  {
    id: "g-josefa-care",
    question: "Who looked after Mamá Fefa after you went north?",
    rationale: "Josefa lived thirty more years in Oaxaca. We have no record of anyone caring for her — possibly a whole branch missing.",
    subjectPersonId: "p-josefa",
    askPersonId: "p-rosa",
    relatedEventId: "e-josefa-dies",
    priority: 64,
    status: "open",
  },
  {
    id: "g-juarez",
    question: "Dad mentioned six weeks in Juárez. Do you remember where you stayed?",
    rationale: "The Juárez waypoint is our lowest-confidence canon event (0.49) and rests on a single secondhand mention.",
    subjectPersonId: "p-tomas",
    askPersonId: "p-elena",
    relatedEventId: "e-juarez",
    priority: 55,
    status: "open",
  },
];

export const mockFamily: Family = {
  id: "fam-alvarez",
  name: "The Alvarez–Chen Family",
  inviteCode: "LEMON-TREE",
  people,
  places,
  events,
  memories,
  gaps,
};

/** Maya is the Initiator persona; Rosa is the Elder persona. */
export const INITIATOR_ID = "p-maya";
export const ELDER_ID = "p-rosa";

/** Seed thread for the AI Interviewer, already working the top gap. */
export const seedChat: ChatMessage[] = [
  {
    id: "c-1",
    role: "agent",
    text: "Hola Rosa. It's me again — thank you for the story about the lemon tree yesterday. I listened to it twice.",
    createdAt: "2026-09-19T15:00:00Z",
  },
  {
    id: "c-2",
    role: "agent",
    text: "There's one thing the family has never written down, and only you can tell it. You and Tomás left Oaxaca in the spring of 1968. What made you decide to go?",
    createdAt: "2026-09-19T15:00:04Z",
    gapId: "g-why-leave",
  },
];
